package mcp

// readTools returns the read-only tool definitions that call existing admin API routes.
// Each tool corresponds to one GET endpoint in /api/v1/admin.
func readTools() []ToolDef {
	return []ToolDef{
		{
			Name:        "get_views",
			Level:       LevelRead,
			Scope:       "metrics:read",
			Method:      "GET",
			Path:        "/views",
			Description: "Viewing sessions by day, hour, weekday, timezone; completion by weekday; retention curve; drop episodes and resume behavior. Period 7/30/90 days.",
			Summary:     "Sessions, completion, retention and drop analysis",
			Params: []Param{
				{Name: "period", Type: "integer", Description: "Window in days.", Enum: []string{"7", "30", "90"}},
			},
		},
		{
			Name:        "list_top_anime",
			Level:       LevelRead,
			Scope:       "metrics:read",
			Method:      "GET",
			Path:        "/catalog",
			Description: "Paginated anime table: sessions, watch hours, completion rate, new viewers, quadrant (popularity vs completion), genres, formats, languages, new vs back catalog. Filter by format (all, tv, movie, ova). Period 7/30/90 days.",
			Summary:     "Top anime, genres, formats and catalog analysis",
			Params: []Param{
				{Name: "period", Type: "integer", Description: "Window in days.", Enum: []string{"7", "30", "90"}},
				{Name: "format", Type: "string", Description: "Filter: all, tv, movie, ova.", Enum: []string{"all", "tv", "movie", "ova"}},
				{Name: "limit", Type: "integer", Description: "Pagination limit (default 50, max 200)."},
				{Name: "offset", Type: "integer", Description: "Pagination offset."},
			},
		},
		{
			Name:        "get_users_summary",
			Level:       LevelRead,
			Scope:       "metrics:read",
			Method:      "GET",
			Path:        "/users/summary",
			Description: "User count by segment (new, regular, power, dormant, at_risk, never_watched), seniority (age buckets), and active sessions. No period parameter.",
			Summary:     "User segments, seniority and active sessions",
			Params:      []Param{},
		},
		{
			Name:        "list_users",
			Level:       LevelRead,
			Scope:       "metrics:read",
			Method:      "GET",
			Path:        "/users",
			Description: "Paginated user directory: user_id, created_at, last_activity, sessions, watch_hours, segment. Token cannot search (q) or sort by pseudo. Allowed sort: user_id, created_at, last_activity, sessions, watch_hours, pseudo (admin only).",
			Summary:     "User directory with segments and activity",
			Params: []Param{
				{Name: "limit", Type: "integer", Description: "Pagination limit (default 50, max 200)."},
				{Name: "offset", Type: "integer", Description: "Pagination offset."},
				{Name: "segment", Type: "string", Description: "Filter by segment.", Enum: []string{"new", "regular", "power", "dormant", "at_risk", "never_watched"}},
				{Name: "sort", Type: "string", Description: "Sort by (token: user_id, created_at, last_activity, sessions, watch_hours; admin: also pseudo).", Enum: []string{"user_id", "created_at", "last_activity", "sessions", "watch_hours", "pseudo"}},
				{Name: "dir", Type: "string", Description: "Direction: asc or desc (default desc).", Enum: []string{"asc", "desc"}},
			},
		},
		{
			Name:        "get_user",
			Level:       LevelRead,
			Scope:       "metrics:read",
			Method:      "GET",
			Path:        "/users/{id}",
			Description: "User detail: id, created_at, segment, recent sessions (10), progress on ongoing episodes (50). No email. Token does not see pseudo.",
			Summary:     "User profile, recent sessions and progress",
			Params: []Param{
				{Name: "id", Type: "string", Description: "User ID (integer).", Required: true, In: "path"},
			},
		},
		{
			Name:        "get_growth",
			Level:       LevelRead,
			Scope:       "metrics:read",
			Method:      "GET",
			Path:        "/growth",
			Description: "Growth metrics: DAU/WAU/MAU, stickiness, signups per week, cumulative users, funnel (signup→first→3 episodes→J7→J30), retention cohorts (J1/J7/J14/J30), time-to-first-session buckets, churn. Period 7/30/90 days. Contains cohorts and funnel keys in response.",
			Summary:     "DAU/WAU/MAU, funnel, cohorts and churn",
			Params: []Param{
				{Name: "period", Type: "integer", Description: "Window in days.", Enum: []string{"7", "30", "90"}},
			},
		},
		{
			Name:        "get_retention",
			Level:       LevelRead,
			Scope:       "metrics:read",
			Method:      "GET",
			Path:        "/growth",
			Description: "Retention cohorts from growth endpoint: signup weeks and J1/J7/J14/J30 retention %. Period 7/30/90 days. Extracts cohorts from get_growth response.",
			Summary:     "Retention cohorts by signup week",
			Params: []Param{
				{Name: "period", Type: "integer", Description: "Window in days.", Enum: []string{"7", "30", "90"}},
			},
		},
		{
			Name:        "get_funnel",
			Level:       LevelRead,
			Scope:       "metrics:read",
			Method:      "GET",
			Path:        "/growth",
			Description: "Signup funnel from growth endpoint: signup, first session, 3 episodes, active at J7, active at J30 with conversion %. Period 7/30/90 days. Extracts funnel from get_growth response.",
			Summary:     "Signup funnel and activation stages",
			Params: []Param{
				{Name: "period", Type: "integer", Description: "Window in days.", Enum: []string{"7", "30", "90"}},
			},
		},
		{
			Name:        "get_player_health",
			Level:       LevelDiagnostic,
			Scope:       "diagnostics:read",
			Method:      "GET",
			Path:        "/playback/health",
			Description: "Player health: active sessions (null if not measured), error rate (errors/sessions), startup p50/p95 (not measured), sources count and failing, cache data. Period 7/30/90 days.",
			Summary:     "Playback errors, startup latency and source health",
			Params: []Param{
				{Name: "period", Type: "integer", Description: "Window in days.", Enum: []string{"7", "30", "90"}},
			},
		},
		{
			Name:        "get_watch_status",
			Level:       LevelDiagnostic,
			Scope:       "diagnostics:read",
			Method:      "GET",
			Path:        "/watch",
			Description: "Automatic monitoring: the state of each watch rule (ok, near, breached, not_measured) with its value and threshold, the last evaluations, and the before/after of the fixes triggered by a breach (verdict open, pending, improved or not_improved). Start here when woken up by a watch webhook or on a schedule. Reading evaluates nothing; the server evaluates every minute.",
			Summary:     "State of the watch rules and effect of past fixes",
		},
		{
			Name:        "list_playback_errors",
			Level:       LevelDiagnostic,
			Scope:       "diagnostics:read",
			Method:      "GET",
			Path:        "/playback/errors",
			Description: "Grouped playback errors (code, anime_id, episode, source): occurrence count, first_seen, last_seen. Filter by code or since. Paginated. since max 90 days back.",
			Summary:     "Playback errors grouped by code and context",
			Params: []Param{
				{Name: "code", Type: "string", Description: "Filter by error code."},
				{Name: "since", Type: "string", Description: "Errors since RFC3339 or YYYY-MM-DD (max 90 days back)."},
				{Name: "limit", Type: "integer", Description: "Pagination limit (default 50, max 200)."},
				{Name: "offset", Type: "integer", Description: "Pagination offset."},
			},
		},
		{
			Name:        "get_errors_summary",
			Level:       LevelDiagnostic,
			Scope:       "diagnostics:read",
			Method:      "GET",
			Path:        "/playback/errors/summary",
			Description: "Error summary: total count and KPI vs previous period, by code with count and probable cause (file list), daily trend by code. Period 7/30/90 days.",
			Summary:     "Error summary, probable causes and daily trend",
			Params: []Param{
				{Name: "period", Type: "integer", Description: "Window in days.", Enum: []string{"7", "30", "90"}},
			},
		},
		{
			Name:        "get_sources_health",
			Level:       LevelDiagnostic,
			Scope:       "diagnostics:read",
			Method:      "GET",
			Path:        "/playback/sources",
			Description: "Source/tracker failures: count, share %, last seen (RFC3339). Attempts per source not measured. Period 7/30/90 days.",
			Summary:     "Source failure rates and health status",
			Params: []Param{
				{Name: "period", Type: "integer", Description: "Window in days.", Enum: []string{"7", "30", "90"}},
			},
		},
		{
			Name:        "get_costs",
			Level:       LevelRead,
			Scope:       "metrics:read",
			Method:      "GET",
			Path:        "/costs",
			Description: "Usage (watch_hours, sessions, active_users, peak_concurrent) and costs (server, bandwidth, storage, total) with measured flags. Money is null with measured:false when cost inputs are missing. Period 7/30/90 days.",
			Summary:     "Usage metrics and cost estimates",
			Params: []Param{
				{Name: "period", Type: "integer", Description: "Window in days.", Enum: []string{"7", "30", "90"}},
			},
		},
		{
			Name:        "list_issues",
			Level:       LevelDiagnostic,
			Scope:       "diagnostics:read",
			Method:      "GET",
			Path:        "/issues",
			Description: "Paginated issues (findings raised by Claude or admin): id, created_at, updated_at, severity (low, medium, high, critical), status (new, in_progress, resolved), title. Filter by status or severity.",
			Summary:     "Issues and findings list",
			Params: []Param{
				{Name: "status", Type: "string", Description: "Filter by status.", Enum: []string{"new", "in_progress", "resolved"}},
				{Name: "severity", Type: "string", Description: "Filter by severity.", Enum: []string{"low", "medium", "high", "critical"}},
				{Name: "limit", Type: "integer", Description: "Pagination limit (default 50, max 200)."},
				{Name: "offset", Type: "integer", Description: "Pagination offset."},
			},
		},
		{
			Name:        "get_issue",
			Level:       LevelDiagnostic,
			Scope:       "diagnostics:read",
			Method:      "GET",
			Path:        "/issues/{id}",
			Description: "Issue detail: id, status, severity, title, evidence, suggested_fix, source, notes, created_at, updated_at.",
			Summary:     "Issue detail and resolution history",
			Params: []Param{
				{Name: "id", Type: "string", Description: "Issue ID.", Required: true, In: "path"},
			},
		},
	}
}
